### ISSUE TITLE
Upload error: unable to open image

### ISSUE THREAD

**Issue by allyssonharry** [onmotion/yii2-gallery#1]
Hello Guy,

I trying to upload some images but the error is output: 

Modal title:
**13600043_1170163906358463_8482439776291589314_n.jpg: SyntaxError: Unexpected token U in JSON at position 0.**

Modal content:
**Upload error: unable to open image `/var/www/html/yii2-app-ccer/uploads/gallery/My Photos/57d8a99d557c0.jpg': No such file or directory @ error/blob.c/OpenBlob/2641**

Please can you help me?

Great work. Thanks!

**Comment by onmotion** [comment]
Hi! 

Which template you have installed, basic or advanced? Can you show stack trace for this issue?

**Comment by allyssonharry** [comment]
Hi Alexandr,
excuse me for answering only now. Follows the stack trace:

I am using the advenced template. 

**PHP Stack Trace, from "Gallery\DefaultController > actionFileUpload()"**

PHP Notice 'yii\base\ErrorException' with message 'Array to string conversion' 
in /var/www/html/MyApp/protected/modules/gallery/controllers/DefaultController.php:91
Stack trace:
#0 /var/www/html/MyApp/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): ::call_user_func_array:{/var/www/html/MyApp/protected/vendor/yiisoft/yii2/base/InlineAction.php:55}()
#1 /var/www/html/MyApp/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams()
#2 /var/www/html/MyApp/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction()
#3 /var/www/html/MyApp/protect
_NOTE_
ed/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction()
#4 /var/www/html/MyApp/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest()
#5 /var/www/html/MyApp/index.php(25): yii\base\Application->run()
#6 {main}

Thank you!

**Comment by allyssonharry** [comment]
Hi Alexandr,

I could look it up ...
I thought it was a problem with the script, but I realized that the error was only rename the path where the files would be stored. Modified the files are: **DefaultController.php, galleryItem.php, view.php (in view folder)**

Thank you so much guy.

**Comment by onmotion** [comment]
I'll be glad if you post the modified code (may be pull request). Now I refactoring the code and remove Imagick dependency.

Thanks a lot in advance!

**Comment by allyssonharry** [comment]
Hi,
This module is nice and very helpful!
I think he would be better off being easily adaptable to any type of template/theme using yiiframework. In addition to the more. It contains some dependancy (like: imagick as you mentioned above). I am making some modifications so can. I'll post the modifications you to validate before.

I have some problems above because i'm using modified template as base yii-advanced.

*\* NOTE, your module works fine with advenced template of yii2. **

Thanks guy.
