### ISSUE TITLE
Create page not Shown

### ISSUE THREAD

**Issue by baladewa88** [onmotion/yii2-gallery#10]
Hi good morning
I already installed and do all step for installation. The gallery can access from host/gallery but I can add new gallery. When click + icon it looks like shown some modal because the screen darker than before but nothing is shown up? what is wrong?
![on motion error](https://user-images.githubusercontent.com/1809276/59958578-130adc80-94d3-11e9-9eb9-19ddd7d7a14e.PNG)

I try to access it manually to host/gallery/default/create and the create page is shown but can not save

thanks in advance

**Comment by baladewa88** [comment]
![on motion error 2](https://user-images.githubusercontent.com/1809276/59958595-654bfd80-94d3-11e9-8d82-229ece26a3d1.PNG)

**Comment by baladewa88** [comment]
in my console wrote this as error
![image](https://user-images.githubusercontent.com/1809276/59958703-c2947e80-94d4-11e9-8cf5-03b37fdc8b60.png)

**Comment by onmotion** [comment]
Hi.
Please, try in chrome.

**Comment by onmotion** [comment]
Close because no feedback
