### ISSUE TITLE
Image is not uploading at all

### ISSUE THREAD

**Issue by bogdan-baerov** [onmotion/yii2-gallery#14]
Greetings! I've just found this awesome module and first of all I want to thank you for doing this.

I have an issue that doesn't let me upload any image, I just press on the "Upload image" text, then I browse one image file(png or jpg), and press on enter or just "okay" in order to upload it, but nothing happenes, the "Upload photo" element just goes back to the initial state and I have no error, and no insertion to database, I can create endless galleries though, can't upload any images to any of the galleries and I'm kinda stuck.

Thank you in advance

**Comment by utking** [comment]
@Baerov - perhaps it was a change in how events are being triggered in https://plugins.krajee.com/file-input/plugin-events. If you remove the fileunlock handler and put a proper event (reload after the upload is done), it will be working. However, this module seems to be abandoned, and you will have to fix it by yourself.

**Comment by bogdan-baerov** [comment]
Thank you for the message, I didn't expect anyone to reply to this after so much time. 

Though a useful tip. I moved to Symfony, Yii2 is kinda outdated for 2021 sadly, wish they would make a major update to it one day.
