### ISSUE TITLE
You can not see images

### ISSUE THREAD

**Issue by emarkov111** [onmotion/yii2-gallery#2]
Hi.
I have set up, create an album, upload pictures, but they are not displayed.
I'm sorry for my bad english.
![img](https://cloud.githubusercontent.com/assets/12261819/19184805/78f8fe52-8c87-11e6-9c46-14aa683a6a38.png)

**Comment by onmotion** [comment]
Hello.

I Need more info about your actions.
You can speak russian...

**Comment by emarkov111** [comment]
Я все сделал по инструкции, подключил пример, создал, альбом, добавил картинки и их не видно. Смотри скрин
![img](https://cloud.githubusercontent.com/assets/12261819/19184990/5429ca24-8c88-11e6-9ce5-4abd3e79948f.png)
![images1](https://cloud.githubusercontent.com/assets/12261819/19184991/56eda9ce-8c88-11e6-96e5-8589226afe55.png)

**Comment by onmotion** [comment]
Что в консоли? Куда ведет src изображения? Файлы фактически появились на сервере?

**Comment by emarkov111** [comment]
В консоле чисто, файлы появились, кусок html 
 </div></div><div id="gallery-links"><a class="gallery-item" href="/img/gallery/test0/57f75b4e97dec
.jpg" title="test0" data-id="1"><img src="/img/gallery/test0/thumb/57f75b4e97dec.jpg" alt=""></a>
<a class="gallery-item" href="/img/gallery/test0/57f75bca8a194.png" title="test0" data-id="2"><img src
="/img/gallery/test0/thumb/57f75bca8a194.png" alt=""></a></div><div id="blueimp-gallery" class="blueimp-gallery
 blueimp-gallery-controls"><div class="slides"></div><h3 class="title"></h3><a class="prev">‹</a><a class
="next">›</a><a class="close">×</a><a class="play-pause"></a></div>                </div>

**Comment by emarkov111** [comment]
извини

```
 </div></div><div id="gallery-links"><a class="gallery-item" href="/img/gallery/test0/57f75b4e97dec
.jpg" title="test0" data-id="1"><img src="/img/gallery/test0/thumb/57f75b4e97dec.jpg" alt=""></a>
<a class="gallery-item" href="/img/gallery/test0/57f75bca8a194.png" title="test0" data-id="2"><img src
="/img/gallery/test0/thumb/57f75bca8a194.png" alt=""></a></div><div id="blueimp-gallery" class="blueimp-gallery
 blueimp-gallery-controls"><div class="slides"></div><h3 class="title"></h3><a class="prev">‹</a><a class
="next">›</a><a class="close">×</a><a class="play-pause"></a></div>                </div>
```

**Comment by onmotion** [comment]
Какой ответ сервер выдает если напрямую запросить /img/gallery/test0/thumb/57f75b4e97dec.jpg ?

**Comment by onmotion** [comment]
В консоли вряд ли будет чисто, должен выдавать как минимум 404 на эти файлы.

**Comment by emarkov111** [comment]
показал картинку
![img2](https://cloud.githubusercontent.com/assets/12261819/19185631/1e9a1334-8c8b-11e6-965e-48038d3445b3.png)

**Comment by onmotion** [comment]
А из виджета запрашивает картинку из frontend?

**Comment by emarkov111** [comment]
где это посмотреть?

**Comment by onmotion** [comment]
ПКМ на картинке и выбрать открыть ссылку в новом окне/вкладке и посмотреть полный адрес.

**Comment by emarkov111** [comment]
http://192.168.0.59/img/gallery/test0/thumb/57f75b4e97dec.jpg

**Comment by onmotion** [comment]
А как сконфигурирован сервер, http://192.168.0.59 куда ведет?

**Comment by emarkov111** [comment]
а файл ложит правильно, где путь поправить чтоб выдел картинку

**Comment by emarkov111** [comment]
создает директории, загружает , удаляет файл правильно, но не показывает картинку

**Comment by onmotion** [comment]
Вам нужно немного почитать про абсолютные и относительные пути. В мануале написано как сконфигурировать Apache или Nginx для работы с advanced template, скорее всего Вы это сделали неверно. Root директория должна вести на /path/to/yii-application/frontend/web/ 
Почему бы Вам не установить basic app, там нет разделения на front  и back и настройка попроще с одним конфигом.

**Comment by emarkov111** [comment]
Спасибо разобрался, проблемма таки была в путях к файлу.

**Comment by onmotion** [comment]
Отлично!
Удачного дня.
