### ISSUE TITLE
upload and display issue

### ISSUE THREAD

**Issue by avishal** [onmotion/yii2-gallery#3]
Hello,
first i want to thank you for making such a great module.
I have integrated the code in my application, it works fine on the localhost, but when i have tried the same on live server it does not work.
1st issue is when the image is uploaded it generates only black image.
2nd issue is when is select multiple images for upload, it only save 1 image.
3rd issue is im unable to upload new or edit the gallery
im using godday server for testing.
Please reply if you need more details on it
Thank you

**Comment by onmotion** [comment]
Hi!
Please compare php.ini settings of your dev and prod servers, especially such as max file size and memory limit. If everything is OK write them here.

**Comment by avishal** [comment]
I dont have php.ini of server. I use a shared server, so how can i access that file?
I'm able to upload small and large file but after processing only smaller files are saved properly. But for larger files (like some file size greater than 800 kb ) are saved but only black image.
Below i have attached the screenshot. There in brown box is the file with size 900 kb and another with red box is file size 22 kb.
![untitled](https://cloud.githubusercontent.com/assets/1900957/20480955/b48230be-b00a-11e6-9118-bb8ba926d9e6.png)

**Comment by onmotion** [comment]
Try to write to your provider how you can change php.ini config. You should
set like that:
upload_max_filesize = 20M
post_max_size = 20M

---

WBR, Alexandr Kozhevnikov.

2016-11-21 14:17 GMT+03:00 Vishal notifications@github.com:

**Comment by avishal** [comment]
Ok. Thanks for your quick reply.
