### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 7

### ISSUE THREAD

**Issue by dbd5** [onmotion/yii2-gallery#4]
Hi @onmotion ,

It seems a tiny bug is triggered by the create code, I took a look and in the module you've got a comment that **//route doesn't work.** It appears the Urlmanager rule fails dependending on its position in the config.

I replaced it with the following more specific rule, it should work anywhere in the config baring other conflict. You may close this issue if you agree, hopefully this will help someone.

`'gallery/<action:[\w-]+>' => 'gallery/default/<action>',`

Great work in the module, thanks

Adam

**Comment by onmotion** [comment]
What action caused the error?
It was a conflict with the rules in the app config file?

**Comment by dbd5** [comment]
The error happens anytime you click the + button to initiate CREATE action
