### ISSUE TITLE
How to upload a photo

### ISSUE THREAD

**Issue by clambacalin** [onmotion/yii2-gallery#9]
I installed the module, everything is working ok but how to upload a photo?
When i click "Upload photo" i only see a spining icon. If i click it, then i can browse my computer to select photos but after that nothing happens. There is no upload button.
![Screenshot_2](https://user-images.githubusercontent.com/19192939/57327288-3e01c280-7117-11e9-8099-0948bcd2a754.png)

**Comment by onmotion** [comment]
Hi.

Please check your browser console output on error

**Comment by clambacalin** [comment]
Already did that with chrome and firefox, there is no error. If i play with inspector then i can make the input appear, i select some photos and then what? there is no upload button. I also checked in code in view.php, there is no upload button

**Comment by onmotion** [comment]
Please post your view file code and show which method it rendering, render, partial, ajax?

**Comment by clambacalin** [comment]
I did not create any view file. I simply followed the install instructions from readme and then go to projectname/gallery and it worked. Only thing is that i don't know how to upload photos. 
I see in DefaultController.php that render method is used.

**Comment by onmotion** [comment]
I'll check it out soon.
